/**
 * sb2nov LaTeX resume template.
 *
 * Implements the LatexTemplate interface. Render functions produce
 * LaTeX structural commands; user content is NOT escaped here
 * (the latex-compiler handles escaping before calling template functions).
 *
 * Based on: https://github.com/sb2nov/resume
 * Reference output: zettelkasten/proj/job-hunting/applications/guidepoint/senior-security-engineer/resume.tex
 */

import type { LatexTemplate, IRSection, ResumeHeader } from '../types'

export const sb2nov: LatexTemplate = {
  preamble: `%-------------------------
% Resume in LaTeX
% Based on sb2nov template (https://github.com/sb2nov/resume)
% Generated by Forge Resume Builder
% License: MIT
%------------------------

\\documentclass[letterpaper,10pt]{article}

\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}
% glyphtounicode not needed with tectonic (XeTeX handles Unicode natively)

\\pagestyle{fancy}
\\fancyhf{}
\\fancyfoot{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

\\addtolength{\\oddsidemargin}{-0.55in}
\\addtolength{\\evensidemargin}{-0.55in}
\\addtolength{\\textwidth}{1.1in}
\\addtolength{\\topmargin}{-.55in}
\\addtolength{\\textheight}{1.1in}

\\urlstyle{same}
\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}

\\titleformat{\\section}{
  \\vspace{-4pt}\\scshape\\raggedright\\large
}{}{0em}{}[\\color{black}\\titlerule \\vspace{-5pt}]

% pdfgentounicode not needed with tectonic (XeTeX)

\\newcommand{\\resumeItem}[1]{\\item\\small{#1 \\vspace{-2pt}}}
\\newcommand{\\resumeSubheading}[4]{
  \\vspace{-1pt}\\item
    \\begin{tabular*}{0.97\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
      \\textbf{#1} & #2 \\\\
      \\textit{\\small #3} & \\textit{\\small #4} \\\\
    \\end{tabular*}\\vspace{-5pt}
}
\\newcommand{\\resumeSubSubheading}[2]{
    \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}
      \\textit{\\small #1} & \\textit{\\small #2} \\\\
    \\end{tabular*}\\vspace{-5pt}
}
\\newcommand{\\resumeProjectHeading}[2]{
    \\item
    \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}
      \\small #1 & #2 \\\\
    \\end{tabular*}\\vspace{-7pt}
}
\\newcommand{\\resumeSubItem}[1]{\\resumeItem{#1}\\vspace{-4pt}}
\\renewcommand{\\labelitemii}{$\\circ$}
\\newcommand{\\resumeSubHeadingListStart}{\\begin{itemize}[leftmargin=*]}
\\newcommand{\\resumeSubHeadingListEnd}{\\end{itemize}}
\\newcommand{\\resumeItemListStart}{\\begin{itemize}}
\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-5pt}}
`,

  renderHeader(header: ResumeHeader): string {
    const lines: string[] = []
    lines.push('\\begin{center}')
    lines.push(`    \\textbf{\\Huge \\scshape ${header.name}} \\\\ \\vspace{1pt}`)

    if (header.tagline) {
      lines.push(`    \\small ${header.tagline} \\\\ \\vspace{3pt}`)
    }

    // Contact line
    const parts: string[] = []
    if (header.location) {
      parts.push(`\\small ${header.location}`)
    }
    if (header.email) {
      parts.push(`\\href{mailto:${header.email}}{\\underline{${header.email}}}`)
    }
    if (header.phone) {
      // Strip non-digits for tel: link, keep formatted for display
      const digits = header.phone.replace(/\D/g, '')
      parts.push(`\\href{tel:+${digits}}{\\underline{${header.phone}}}`)
    }
    if (header.linkedin) {
      parts.push(`\\href{${header.linkedin}}{\\underline{LinkedIn}}`)
    }
    if (header.github) {
      parts.push(`\\href{${header.github}}{\\underline{GitHub}}`)
    }
    if (header.website) {
      parts.push(`\\href{${header.website}}{\\underline{Website}}`)
    }

    if (parts.length > 0) {
      lines.push(`    ${parts.join(' $|$\n    ')}`)
    }

    lines.push('\\end{center}')
    return lines.join('\n')
  },

  renderSection(section: IRSection): string {
    switch (section.type) {
      case 'summary':
        return renderSummarySection(section)
      case 'experience':
        return renderExperienceSection(section)
      case 'skills':
        return renderSkillsSection(section)
      case 'education':
        return renderEducationSection(section)
      case 'projects':
        return renderProjectsSection(section)
      case 'certifications':
        return renderCertificationsSection(section)
      case 'clearance':
        return renderClearanceSection(section)
      case 'presentations':
        return renderPresentationsSection(section)
      default:
        return sb2nov.renderSectionFallback(section)
    }
  },

  renderSectionFallback(section: IRSection): string {
    const lines: string[] = []
    lines.push(`\\section{${section.title}}`)
    lines.push('  \\resumeSubHeadingListStart')
    for (const item of section.items) {
      if ('content' in item && typeof item.content === 'string') {
        lines.push(`    \\resumeItem{${item.content}}`)
      }
    }
    lines.push('  \\resumeSubHeadingListEnd')
    return lines.join('\n')
  },

  footer: `
%-------------------------------------------
\\end{document}
`,
}

// ── Section renderers ────────────────────────────────────────────────

function renderSummarySection(section: IRSection): string {
  const lines: string[] = []
  lines.push(`\\section{${section.title}}`)
  for (const item of section.items) {
    if (item.kind === 'summary') {
      lines.push(item.content)
    }
  }
  return lines.join('\n')
}

function renderExperienceSection(section: IRSection): string {
  const lines: string[] = []
  lines.push(`\\section{${section.title}}`)
  lines.push('  \\resumeSubHeadingListStart')

  let isFirst = true
  for (const item of section.items) {
    if (item.kind !== 'experience_group') continue

    if (!isFirst) lines.push('')
    if (!isFirst) lines.push('    \\vspace{5pt}')
    isFirst = false

    // First subheading uses \resumeSubheading, subsequent use \resumeSubSubheading
    for (let i = 0; i < item.subheadings.length; i++) {
      const sub = item.subheadings[i]

      if (i === 0) {
        lines.push('')
        lines.push(`    \\resumeSubheading`)
        lines.push(`      {${item.organization}}{}`)
        lines.push(`      {${sub.title}}{${sub.date_range}}`)
      } else {
        lines.push('    \\vspace{5pt}')
        lines.push(`    \\resumeSubSubheading`)
        lines.push(`      {${sub.title}}{${sub.date_range}}`)
      }

      lines.push('      \\resumeItemListStart')
      for (const bullet of sub.bullets) {
        lines.push(`        \\resumeItem{${bullet.content}}`)
      }
      lines.push('      \\resumeItemListEnd')
    }
  }

  lines.push('  \\resumeSubHeadingListEnd')
  return lines.join('\n')
}

function renderSkillsSection(section: IRSection): string {
  const lines: string[] = []
  lines.push(`\\section{${section.title}}`)
  lines.push(' \\begin{itemize}[leftmargin=0.15in, label={}]')
  lines.push('    \\small{\\item{')

  for (const item of section.items) {
    if (item.kind !== 'skill_group') continue
    for (const cat of item.categories) {
      lines.push(`     \\textbf{${cat.label}}{: ${cat.skills.join(', ')}} \\\\`)
    }
  }

  lines.push('    }}')
  lines.push(' \\end{itemize}')
  return lines.join('\n')
}

function renderEducationSection(section: IRSection): string {
  const lines: string[] = []
  lines.push(`\\section{${section.title}}`)
  lines.push('  \\resumeSubHeadingListStart')

  for (const item of section.items) {
    if (item.kind !== 'education') continue

    const eduType = item.education_type ?? 'degree'

    if (eduType === 'self_taught') {
      // Self-taught: freeform text as a simple resumeItem
      const content = item.edu_description ?? item.degree
      lines.push(`    \\resumeItem{${content}}`)
    } else if (eduType === 'certificate') {
      // Certificate: title + expiration on line 1, issuing_body + credential on line 2
      const title = item.degree
      const expDate = item.date ? `Exp. ${item.date}` : ''
      const issuer = item.issuing_body ?? item.institution
      const credPart = item.credential_id ? ` -- Credential ID: ${item.credential_id}` : ''
      const line2 = issuer ? `${issuer}${credPart}` : credPart.replace(/^ -- /, '')
      lines.push(`    \\resumeSubheading`)
      lines.push(`      {${title}}{${expDate}}`)
      lines.push(`      {${line2}}{}`)
    } else if (eduType === 'course') {
      // Course: title + date on line 1, institution + location on line 2
      const title = item.degree
      const date = item.date ?? ''
      const instPart = item.institution ?? ''
      const locPart = item.location ? `, ${item.location}` : ''
      const line2 = `${instPart}${locPart}`
      lines.push(`    \\resumeSubheading`)
      lines.push(`      {${title}}{${date}}`)
      lines.push(`      {${line2}}{}`)
    } else {
      // Degree (default): institution + location on line 1, degree info + date on line 2
      const location = item.location ?? ''
      const degreeType = item.degree_type ?? ''
      const field = item.field ?? null
      // Build degree string: "M.S. in Computer Science" or fall back to perspective content
      let degreeLine: string
      if (degreeType && field) {
        degreeLine = `${degreeType} in ${field}`
      } else if (degreeType) {
        degreeLine = degreeType
      } else {
        degreeLine = item.degree
      }
      if (item.gpa) {
        degreeLine += `, GPA: ${item.gpa}`
      }
      const dateRange = item.date ?? ''
      lines.push(`    \\resumeSubheading`)
      lines.push(`      {${item.institution}}{${location}}`)
      lines.push(`      {${degreeLine}}{${dateRange}}`)
    }
  }

  lines.push('  \\resumeSubHeadingListEnd')
  return lines.join('\n')
}

function renderProjectsSection(section: IRSection): string {
  const lines: string[] = []
  lines.push(`\\section{${section.title}}`)
  lines.push('  \\resumeSubHeadingListStart')

  for (const item of section.items) {
    if (item.kind !== 'project') continue
    lines.push(`    \\resumeProjectHeading`)
    lines.push(`      {\\textbf{${item.name}}}{${item.date ?? ''}}`)

    if (item.bullets.length > 0) {
      lines.push('      \\resumeItemListStart')
      for (const bullet of item.bullets) {
        lines.push(`        \\resumeItem{${bullet.content}}`)
      }
      lines.push('      \\resumeItemListEnd')
    }
  }

  lines.push('  \\resumeSubHeadingListEnd')
  return lines.join('\n')
}

function renderCertificationsSection(section: IRSection): string {
  const lines: string[] = []
  lines.push(`\\section{${section.title}}`)
  lines.push('  \\begin{itemize}[leftmargin=0.15in, label={}]')
  lines.push('    \\small{\\item{')

  for (const item of section.items) {
    if (item.kind !== 'certification_group') continue
    for (const cat of item.categories) {
      const certNames = cat.certs.map(c => c.name).join(', ')
      lines.push(`     \\textbf{${cat.label}}{: ${certNames}} \\\\`)
    }
  }

  lines.push('    }}')
  lines.push(' \\end{itemize}')
  return lines.join('\n')
}

function renderClearanceSection(section: IRSection): string {
  const lines: string[] = []
  lines.push(`\\section{${section.title}}`)

  for (const item of section.items) {
    if (item.kind !== 'clearance') continue
    lines.push(item.content)
  }

  return lines.join('\n')
}

function renderPresentationsSection(section: IRSection): string {
  const lines: string[] = []
  lines.push(`\\section{${section.title}}`)
  lines.push('  \\resumeSubHeadingListStart')

  for (const item of section.items) {
    if (item.kind !== 'presentation') continue
    const titlePart = `\\textbf{\`\`${item.title}''}`
    const venuePart = item.venue ? ` $|$ \\emph{${item.venue}${item.date ? `, ${item.date}` : ''}}` : ''
    lines.push(`    \\resumeProjectHeading`)
    lines.push(`      {${titlePart}${venuePart}}{}`)

    if (item.bullets.length > 0) {
      lines.push('      \\resumeItemListStart')
      for (const bullet of item.bullets) {
        lines.push(`        \\resumeItem{${bullet.content}}`)
      }
      lines.push('      \\resumeItemListEnd')
    }
  }

  lines.push('  \\resumeSubHeadingListEnd')
  return lines.join('\n')
}
